title: "Crown Creatives v2"
description: "Clean rebuild of the Crown Creatives website."

url: "https://pmr76.github.io"
baseurl: "/crowncreatives"

markdown: kramdown

version: 14

include:
  - _pages

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: default
      seo:
        type: website
